In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Telecom Churn Data

The data comes from [here](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383).  It contains information about a telecomunications company and customer churn.  Your goal is to describe the customer churn as well as get some idea of factors involved in churn.

In [4]:
telecom = pd.read_csv('../data/telecom_churn.csv')

In [9]:
telecom.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [10]:
type(telecom)

pandas.core.frame.DataFrame

In [5]:
telecom.shape

(3333, 20)

In [6]:
telecom.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [7]:
telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
State                     3333 non-null object
Account length            3333 non-null int64
Area code                 3333 non-null int64
International plan        3333 non-null object
Voice mail plan           3333 non-null object
Number vmail messages     3333 non-null int64
Total day minutes         3333 non-null float64
Total day calls           3333 non-null int64
Total day charge          3333 non-null float64
Total eve minutes         3333 non-null float64
Total eve calls           3333 non-null int64
Total eve charge          3333 non-null float64
Total night minutes       3333 non-null float64
Total night calls         3333 non-null int64
Total night charge        3333 non-null float64
Total intl minutes        3333 non-null float64
Total intl calls          3333 non-null int64
Total intl charge         3333 non-null float64
Customer service calls    3333 non-null int64
Churn                     3333 non-null bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB

In [11]:
telecom['Churn'] = telecom['Churn'].astype('int64')

### Investigating the Distributions

Here are some starting points. Try using these methods on the dataframe and see what questions they help answer.  Also, see if you can produce some visualizations to help tell your story.

1. What was the breakdown of churn or no churn?
  1. `.value_counts()`
  2. `.value_counts(normalize = True)`
  
2. Describe the distribution
  1. `.describe()`
  2. `.describe(include=['object', 'bool'])
  
3. Sort by Total Charge
  1. `.sort_values()`
  2. `.sort_value(by = ['Churn', 'Total day charge'], ascending = [True, False])`
  
4. Group by Useage
  1. `.groupby(['Churn'])['Total day minutes'].describe(percentiles=[])
  2. `.groupby(['Churn'])['Total day minutes'].agg([np.mean, np.std, np.min, np.max])`
  
5. Summary Tables
  1. `.crosstab(telecom['Churn'], telecom['International plan'])`

In [11]:
telecom["Churn"].value_counts()

False    2850
True      483
Name: Churn, dtype: int64

In [12]:
telecom["Churn"].value_counts(normalize = True)

False    0.855086
True     0.144914
Name: Churn, dtype: float64

In [13]:
telecom.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [16]:
telecom["Total day calls"].sort_values()

1397      0
1345      0
1144     30
1989     35
692      36
740      40
3187     40
1322     42
2217     42
2964     44
2885     44
2884     44
2492     45
1346     45
1422     45
415      47
143      47
1273     48
1727     48
2824     48
2134     49
2883     49
2353     51
2626     51
921      51
2315     52
125      52
194      52
360      53
2097     53
       ...
828     147
1746    147
656     147
1814    147
2630    148
1425    148
238     148
1811    148
1018    148
1621    149
989     150
1434    150
767     150
2779    150
1081    150
870     150
2010    151
164     151
3190    151
2350    151
580     151
1719    152
1869    156
2394    157
2392    158
315     158
1057    158
1460    160
468     163
1121    165
Name: Total day calls, Length: 3333, dtype: int64

In [21]:
telecom.sort_values(by = ["Total day minutes"], ascending = [False])

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
365,CO,154,415,No,No,0,350.8,75,59.64,216.5,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True
985,NY,64,415,Yes,No,0,346.8,55,58.96,249.5,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True
2594,OH,115,510,Yes,No,0,345.3,81,58.70,203.4,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True
156,OH,83,415,No,No,0,337.4,120,57.36,227.4,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True
605,MO,112,415,No,No,0,335.5,77,57.04,212.5,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True
975,DE,129,510,No,No,0,334.3,118,56.83,192.1,104,16.33,191.0,83,8.59,10.4,6,2.81,0,True
15,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
1679,OK,82,510,No,No,0,329.8,73,56.07,208.3,120,17.71,267.1,102,12.02,10.6,6,2.86,0,True
2028,SD,93,510,No,No,0,328.1,106,55.78,151.7,89,12.89,303.5,114,13.66,8.7,3,2.35,1,True
197,TX,208,510,No,No,0,326.5,67,55.51,176.3,113,14.99,181.7,102,8.18,10.7,6,2.89,2,True
2412,WI,89,415,No,No,0,326.3,112,55.47,165.1,110,14.03,162.9,97,7.33,7.5,1,2.03,1,True
2824,OR,81,415,No,No,0,324.7,48,55.20,236.4,82,20.09,187.6,78,8.44,13.1,5,3.54,0,True
832,SC,87,408,No,No,0,322.5,106,54.83,204.6,93,17.39,186.2,128,8.38,9.4,4,2.54,2,True
2629,NH,141,415,No,Yes,32,322.4,92,54.81,283.2,107,24.07,209.5,111,9.43,6.7,3,1.81,1,True
3132,NC,161,415,No,No,0,322.3,100,54.79,230.4,135,19.58,241.5,104,10.87,7.8,5,2.11,2,True
1078,ME,80,408,No,No,0,322.3,113,54.79,222.0,95,18.87,162.8,123,7.33,6.7,8,1.81,0,True
901,CT,23,510,No,No,0,321.6,107,54.67,251.6,115,21.39,141.1,158,6.35,11.3,3,3.05,2,True
1334,KS,126,408,No,No,0,321.3,99,54.62,167.9,93,14.27,193.6,106,8.71,8.0,4,2.16,1,True
3322,MD,62,408,No,No,0,321.1,105,54.59,265.5,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True
2572,MN,152,415,No,No,0,317.8,60,54.03,152.9,100,13.00,123.4,63,5.55,10.4,7,2.81,1,True
688,MN,13,510,No,Yes,21,315.6,105,53.65,208.9,71,17.76,260.1,123,11.70,12.1,3,3.27,3,False
815,KY,75,415,No,No,0,314.6,102,53.48,169.8,86,14.43,285.1,100,12.83,5.7,3,1.54,2,True
2696,MI,74,415,No,No,0,314.1,86,53.40,222.4,99,18.90,259.0,121,11.66,12.3,5,3.32,3,True
2259,NC,210,415,No,Yes,31,313.8,87,53.35,147.7,103,12.55,192.7,97,8.67,10.1,7,2.73,3,False
2267,MS,29,510,No,No,0,313.2,103,53.24,216.3,151,18.39,218.4,106,9.83,12.8,4,3.46,2,True
230,MD,93,408,Yes,No,0,312.0,109,53.04,129.4,100,11.00,217.6,74,9.79,10.5,2,2.84,0,True
2573,WV,124,415,No,No,0,312.0,112,53.04,180.0,109,15.30,168.6,94,7.59,12.8,4,3.46,1,True
534,LA,67,510,No,No,0,310.4,97,52.77,66.5,123,5.65,246.5,99,11.09,9.2,10,2.48,4,False
575,SD,114,415,No,Yes,36,309.9,90,52.68,200.3,89,17.03,183.5,105,8.26,14.2,2,3.83,1,False
2677,IA,44,415,No,No,0,308.6,139,52.46,150.8,94,12.82,198.7,66,8.94,7.3,3,1.97,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303,IN,205,510,No,No,0,49.9,123,8.48,150.7,81,12.81,188.2,67,8.47,10.1,4,2.73,2,False
2703,CT,162,408,No,No,0,49.2,121,8.36,143.9,136,12.23,203.0,97,9.14,12.1,13,3.27,1,False
535,NE,194,408,No,No,0,48.4,101,8.23,281.1,138,23.89,218.5,87,9.83,18.2,1,4.91,1,False
2173,KS,47,510,Yes,No,0,47.8,120,8.13,178.9,123,15.21,152.6,96,6.87,13.3,7,3.59,0,True
2158,FL,166,510,Yes,No,0,47.7,89,8.11,264.4,95,22.47,235.2,97,10.58,13.2,3,3.56,0,True
525,OK,176,408,No,No,0,47.4,125,8.06,167.8,90,14.26,163.1,107,7.34,10.5,8,2.84,2,False
1531,DE,138,510,Yes,No,0,46.5,104,7.91,186.0,114,15.81,167.5,95,7.54,9.6,4,2.59,4,True
523,MO,61,408,No,No,0,45.0,108,7.65,151.3,74,12.86,152.9,94,6.88,9.8,6,2.65,2,False
2996,VA,113,408,No,Yes,34,44.9,63,7.63,134.2,82,11.41,168.4,118,7.58,13.3,3,3.59,1,False
1742,HI,79,415,No,No,0,41.9,124,7.12,211.0,95,17.94,237.9,55,10.71,11.4,5,3.08,1,False
527,NJ,95,415,No,Yes,22,40.9,126,6.95,133.4,90,11.34,264.2,91,11.89,11.9,7,3.21,0,False
2707,RI,46,408,No,No,0,40.4,105,6.87,172.4,83,14.65,145.1,89,6.53,9.0,2,2.43,2,False
1461,SC,145,408,No,No,0,39.5,78,6.72,264.3,106,22.47,185.8,90,8.36,10.0,6,2.70,0,False
1687,CT,90,415,No,No,0,37.8,80,6.43,155.3,105,13.20,175.0,111,7.88,14.2,5,3.83,3,False
2241,WA,56,415,No,Yes,29,37.7,115,6.41,144.1,111,12.25,226.6,101,10.20,4.9,3,1.32,1,False
1130,PA,122,415,No,No,0,35.1,62,5.97,180.8,89,15.37,251.6,58,11.32,12.7,2,3.43,1,False
741,NE,66,415,No,No,0,34.0,133,5.78,278.6,61,23.68,129.6,120,5.83,11.5,3,3.11,0,False
685,CO,63,415,No,Yes,32,30.9,113,5.25,187.0,113,15.90,230.8,101,10.39,8.6,7,2.32,1,False
3174,SC,36,408,No,Yes,43,29.9,123,5.08,129.1,117,10.97,325.9,105,14.67,8.6,6,2.32,2,False
2124,KS,43,415,No,No,0,27.0,117,4.59,160.9,97,13.68,279.5,96,12.58,10.7,3,2.89,3,False
1076,WY,53,415,No,Yes,27,25.9,119,4.40,206.5,96,17.55,228.1,64,10.26,6.5,7,1.76,1,False
1621,SC,138,510,No,Yes,21,19.5,149,3.32,140.9,109,11.98,179.7,111,8.09,7.9,1,2.13,0,False
3046,MI,110,510,No,No,0,18.9,92,3.21,258.4,81,21.96,109.6,74,4.93,14.8,4,4.00,1,False
2252,NH,148,408,No,No,0,17.6,121,2.99,161.7,125,13.74,203.1,82,9.14,10.6,6,2.86,1,False
1052,OR,98,415,Yes,No,0,12.5,67,2.13,256.6,90,21.81,169.4,88,7.62,7.7,9,2.08,1,False
1986,WI,70,415,No,No,0,7.9,100,1.34,136.4,83,11.59,156.6,89,7.05,12.1,1,3.27,0,False
2753,OH,134,415,No,No,0,7.8,86,1.33,171.4,100,14.57,186.5,80,8.39,12.9,2,3.48,2,False
2736,OK,127,510,No,Yes,27,2.6,113,0.44,254.0,102,21.59,242.7,156,10.92,9.2,5,2.48,3,False
1397,VT,101,510,No,No,0,0.0,0,0.00,192.1,119,16.33,168.8,95,7.60,7.2,4,1.94,1,False
1345,SD,98,415,No,No,0,0.0,0,0.00,159.6,130,13.57,167.1,88,7.52,6.8,1,1.84,4,True

In [22]:
telecom.groupby(['Churn'])['Total day minutes'].describe(percentiles=[])

        count        mean        std  min    50%    max
Churn
False  2850.0  175.175754  50.181655  0.0  177.2  315.6
True    483.0  206.914079  68.997792  0.0  217.6  350.8

In [23]:
telecom.groupby(['Churn'])['Total day minutes'].agg([np.mean, np.std, np.min, np.max])

             mean        std  amin   amax
Churn
False  175.175754  50.181655   0.0  315.6
True   206.914079  68.997792   0.0  350.8

In [27]:
pd.crosstab(telecom['Churn'], telecom['International plan'])

International plan    No  Yes
Churn
False               2664  186
True                 346  137